### ISSUE TITLE
Merge with upstream

### ISSUE THREAD

**Issue by jangernert** [jscurtu/feedreader-flatpak#1]
Hey,
just had this question about flatpak-support https://github.com/jangernert/FeedReader/issues/283
What is the state of this project right now? Does everything work as expected? (Snap-package still has some problems).
Would you like to merge this into the feedreader-repo and maintain it there? Also, please inform me of any kind of changes that need to be done in FeedReader for this - like renaming the dbus-service-file. Version 2.0 would be a good time to break stuff in order to fully support flatpak :)

**Comment by xarbit** [comment]
Yes it works pretty good actually! ;-) I use it daily .. 
You only need to install portals to get opening link in browser working: 

- xdg-desktop-portal
- xdg-desktop-portal-gtk

The daemon don't start automatic, but it runs once the application was open the first time.
So, it might be useful to include a cli that opens feedreader silently or something similar.
It really is not a show stopper though....

Sure, I can take over the flatpak part, maintain and merge it to feedreader-repo, also for the future.  
Will dive in to version 2.0 and see what's needed to get it up and running in the sandbox. 

You might need to make some compiler parts optional, like goa. 
But I will let you know as soon as I know more.

Right now we only have bundles, we should look how we can set up the resources for a flatpak repository for automatic updates and the full flatpak experience.

**Comment by jangernert** [comment]
So how does the thing with daemon<->UI work inside a flatpak?
Is everything in it's own sandboxed filesystem and the dbus-service-file also sits inside the flatpak or is it installed into the OS filesystem?

Goa is already kind of optional. The only thing required is the client-library. The library only provides functions to call the dbus-API. To make GOA work the dbus-server has to be running. If it's not running then no GOA-accounts will be displayed.
But since GOA is a central part of "Gnome", isn't there a portal to access the online accounts?

Can you tell me what I need to patch in order to conform to flatpak rules? I saw you apply a patch to rename the dbus-service-file. Are there any other files or objects that need to be renamed?

**Comment by xarbit** [comment]
daemon is called regularly over d-bus and executed in the sandbox, yes..  
your service file in flatpak looks like this now:

`
[D-BUS Service]
Name=org.gnome.feedreader
Exec=/app/bin/feedreader-daemon
`

It works as expected, you just cant start it on boot without opening the application before, once it has been started it runs and displays notifications.. 

With goa I am currently doing some testing, I got feedreader master to build the flatpak but no idea if goa works yet as feedreader wont start yet.. WIP
 
Will let you know as soon as I have a running flatpak with version 2.0 and learned what's going on. 

About renaming.. The service file should be renamed from feedreader.service to org.gnome.feedreader.service . The patch can then be removed ..

If you want you can look at the flatpak-builder json file, you will see that there are some renames that flatpak-builder is capable to handle its self. 

`
"rename-appdata-file": "feedreader.appdata.xml",
"rename-desktop-file": "feedreader.desktop",
"rename-icon": "feedreader",
`

flatpak-builder will add a prefix to those files the dbus naming scheme "org.gnome.*".

Also please take a peek at the new patches that arrived this morning, those where needed to keep feedreader secure and a more flatpaky configuration.
https://github.com/jscurtu/feedreader-flatpak/tree/master/patches

**Comment by jangernert** [comment]
I just gave you access to the feedreader repository. Feel free to apply the patches you wrote ;)

**Comment by xarbit** [comment]
Done. Patches merged. 
Feedreader 2.0-dev builds in flatpak too.

**Comment by xarbit** [comment]
FeedReader 2.0-dev builds and works as expected, no more patches needed..  
GOA works too ...
