### ISSUE TITLE
Can't connect to TinyTinyRSS

### ISSUE THREAD

**Issue by yotamN** [jscurtu/feedreader-flatpak#2]
I'm not sure if it's a problem with the flatpak package or feedreader but it worked before so I guess the problem is related to the flatpak package. Anyway, I enter the login details but I get the error message: "Please enter your Login details", the second time I clicked I got:

```
** (feedreader:3): CRITICAL **: file /run/build/feedreader/src/UiUtils.vala: line 96: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (g-dbus-error-quark, 4)
```

**Comment by xarbit** [comment]
Ok, TinyTinyRss was never tested. Thanks for the report. 
I dont have a tinytinyrss instance running anywhere anymore, I switched to feedly a long time ago..
So I will have to see if I can get something up and running to test it myself.. might be missing some permissions. 
What distro are you using? did you install the portal packages? 

edit: ok, i found a hoster for ttrss. 
Will try it out tomorrow. 

Thanks

**Comment by xarbit** [comment]
Please try the updated package.. will close this report, reopen if it is not solved.
Thanks..

**Comment by yotamN** [comment]
Thank you, now I can connect but there is another problem, I can see only 1 article and if I click it I can't see it + I have errors in the terminal:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:15): Gdk-ERROR **: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 200 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[ ERROR ] ArticleView: webview crashed
```

```
[WARNING] ArticleList: updateArticleList - already busy
[WARNING] ArticleList: updateArticleList - queue up update

** (feedreader:3): CRITICAL **: file /run/build/feedreader/src/Widgets/ArticleView.vala: line 508: uncaught error: An exception was raised in JavaScript (WebKitPrintError, 699)

** (feedreader:3): CRITICAL **: file /run/build/feedreader/src/Widgets/ArticleView.vala: line 508: uncaught error: An exception was raised in JavaScript (WebKitPrintError, 699)
[WARNING] ArticleList: updateArticleList - check if ready
```

The first error showed only once and the second error multiple times.

BTW I use Debian unstable with GNOME and X11

**Comment by xarbit** [comment]
do you have the xdg-desktop-portal installed? That is needed to interact with the sandbox and host.

To me it looks like its not there yet in debian, see the links.

https://tracker.debian.org/pkg/xdg-desktop-portal
https://tracker.debian.org/pkg/xdg-desktop-portal-gtk

**Comment by yotamN** [comment]
Yes I have both installed because I'm on unstable

**Comment by yotamN** [comment]
OK I got all the articles now, not sure how, thank you very much but when I click it I still don't see it

**Comment by xarbit** [comment]
fantastic that is nice to hear.. thank you for the feedback.
