### ISSUE TITLE
"WebKit has crashed" constantly

### ISSUE THREAD

**Issue by pyluyten** [jscurtu/feedreader-flatpak#5]
fedora 24, flatpak 0.8.0

installation goes fine
$ flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
$ flatpak install --bundle Téléchargements/feedreader-master-20161229.x86_64.flatpak

Then i can pretty easily pick up my account, it does download feed properly. But each single article says "WebKit has crashed". Progression says 0%. ( Is that "local" webkit or bundled webkit? )
However feedReader is not impacted by WebKit crash as i can select another article or even push to pocket (i did not had to do anything, i just properly retrieved goa)

big up so if i can help it would be cool

**Comment by pyluyten** [comment]
INFO  ] ArticleView: webextension-message: onDocLoaded
[ DEBUG ] ArticleView: loading 100 %
[ DEBUG ] ArticleView: load FINISHED
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:14): Gdk-ERROR **: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 190 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[ ERROR ] ArticleView.setScrollPos: Une exception a été levée dans JavaScript
[ ERROR ] ArticleView: webview crashed

**Comment by pyluyten** [comment]
$ flatpak run org.gnome.Epiphany 
does not works better, so maybe i should close this issue for feedreader & open an issue on flatpak

**Comment by xarbit** [comment]
Do you have XDG-DESKTOP-PORTALS + XDG-DESKTOP-PORTALS-GTK installed? When trying to open a link with a sandbox'd Webbrowser like Epiphany might have issues.. 
Question: 
how many webbrowsers do you have installed?
What FeedAccount are you using?

Anyway, Webkit is not bundled, FeedReader is compiled with WebKit from Flatpak SDK.

**Comment by pyluyten** [comment]
xdg desktop 

xdg-desktop-portal.x86_64                                    0.4-1.fc24                                 @updates
xdg-desktop-portal-gtk.x86_64                                0.3-1.fc24                                 @updates

FeedAccount is old reader.

i tried go get url and run flatpak run org.gnome.Epiphany on this ; but epiphany keeps crashing - actually its worse because it seems it tries again & again until it burns cpu ;)

i just opened one issue directly on flatpak 
https://github.com/flatpak/flatpak/issues/475

**Comment by xarbit** [comment]
I will update the master build on sunday to beta1. Can you try again when the new build is up?

**Comment by pyluyten** [comment]
upstream flatpak issue says it's a duplicate of a general issue with nvidia drivers. until they solve this it might be good to warn nvidia driver users so they know this will not work. (if you think beta1 adds somethings sure i will test ; otherwise i will try with a laptop without nvidia )
