### ISSUE TITLE
Errors starting the app

### ISSUE THREAD

**Issue by ChrisLauinger77** [jscurtu/feedreader-flatpak#6]
When i try to run the app I get the following output - I use nvidia-proprietary drivers:

I tried both the stable and the beta - same result

`flatpak run org.gnome.feedreader &
[1] 13242
christian@debian:~/Downloads$ 
** (feedreader:3): CRITICAL **: file /run/build/feedreader/src/DBusConnection.vala: line 177: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.feedreader was not provided by any .service files (g-dbus-error-quark, 2)
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: determining state

** (feedreader:3): CRITICAL **: file /run/build/feedreader/src/Widgets/MainWindow.vala: line 184: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.feedreader was not provided by any .service files (g-dbus-error-quark, 2)

(feedreader:3): GLib-GObject-CRITICAL **: g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed

(feedreader:3): Gtk-CRITICAL **: gtk_window_set_icon_name: assertion 'GTK_IS_WINDOW (window)' failed

(feedreader:3): Gtk-CRITICAL **: gtk_widget_show_all: assertion 'GTK_IS_WIDGET (widget)' failed

** (feedreader:3): CRITICAL **: feed_reader_dbus_connection_connectSignals: assertion 'window != NULL' failed

** (feedreader:3): CRITICAL **: file /run/build/feedreader/src/FeedReader.vala: line 99: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.feedreader was not provided by any .service files (g-dbus-error-quark, 2)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:112): Gdk-ERROR **: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 207 error_code 2 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[ ERROR ] ArticleView: webview crashed
[ DEBUG ] MainWindow: reloadCSS
[ DEBUG ] MainWindow: setupCSS
`

**Comment by xarbit** [comment]
This is a known problem with upstream flatpak and nvidia drivers. 
#5
